apiVersion: v1
kind: Service
metadata:
  name: lsndpa-gateway-service
  namespace: lsndpa
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: lsndpa-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsndpa-gateway-deployment
  namespace: lsndpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsndpa-gateway
  template:
    metadata:
      labels:
        app: lsndpa-gateway
    spec:
      containers:
      - name: lsndpa-gateway
        image: lsndpa-gateway
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
